build: prep v1.4.0 rc2
moov-io/ach pull request #709
Opened 2020-04-08 00:35 UTC by adamdecaf

2020-04-12 18:16 UTC, wadearnold requested changes
We need documentation on how to use these ValidateOpts somewhere before this release.

2020-04-13 21:13 UTC, adamdecaf commented
@wadearnold I created https://github.com/moov-io/docs/pull/84 for validation documentation.

2020-04-14 16:14 UTC, InfernoJJ approved these changes

2020-04-14 17:29 UTC, wadearnold approved these changes

2020-04-14 17:40 UTC, merged